name: Testing during CI

on:
  pull_request:
    types: [opened, synchronize]
    branches: main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Upload repo artifact
        uses: actions/upload-artifact@v3
        with:
          name: repo-artifact
          path: ./index.js
      - name: Linting
        run: npm run lint

  remark-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: |
          npm install remark-cli remark-preset-lint-consistent
          npx remark . --use remark-preset-lint-consistent --frail
