name: Welcome issue

on:
  issues:
    types: opened

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      # Run command to create issue
      - run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/AlexMartosP/github-actions-testing/issues/${{github.event.issue.id}}/comments \
          -d '{"body":"Thanks for creating this issue.\nThis comment is created by Github Actions."}'
